### ISSUE TITLE
Show time of the message  

### ISSUE THREAD

**Issue by iamshubhankarkhare** [iamshubhankarkhare/Chat-application#13]
Time of the message should also be displayed on lower right or left corner of the message chip.

**Comment by chiteshbansal** [comment]
interested!

**Comment by kitarp29** [comment]
Is this issue still pending?
I can work on it @iamshubhankarkhare

**Comment by iamshubhankarkhare** [comment]
@kitarp29 no its not ..you can take a look at other pending issues .Thanks
